<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import QRCode from 'qrcode'

const props = withDefaults(
  defineProps<{
    value: string
    size?: number
  }>(),
  {
    size: 200,
  },
)

const svg = ref('')
const error = ref(false)

async function generate() {
  if (!props.value) return
  try {
    svg.value = await QRCode.toString(props.value, {
      type: 'svg',
      margin: 1,
      color: {
        dark: '#0f172a',
        light: '#ffffff',
      },
    })
    error.value = false
  } catch {
    error.value = true
  }
}

onMounted(generate)
watch(() => props.value, generate)
</script>

<template>
  <div class="flex flex-col items-center gap-2">
    <div
      class="rounded-lg bg-white p-3"
      :style="{ width: `${size + 24}px`, height: `${size + 24}px` }"
    >
      <div v-if="error" class="flex h-full items-center justify-center text-sm text-slate-500">
        Failed to generate QR code
      </div>
      <!-- eslint-disable vue/no-v-html -- SVG generated by trusted qrcode library -->
      <div
        v-else
        class="flex h-full w-full items-center justify-center [&>svg]:h-full [&>svg]:w-full"
        v-html="svg"
      />
      <!-- eslint-enable vue/no-v-html -->
    </div>
    <p class="text-xs text-slate-500">Scan to open the countdown</p>
  </div>
</template>
